import type { Vehicle } from "@/lib/types"

/**
 * Sample stock used only when Firebase env vars are absent, so the site can
 * be previewed and designed before Firebase is connected. Image `publicId`
 * values below are local paths (served from /public) rather than real
 * Cloudinary public IDs - <VehicleImage> falls back to a normal <Image> for
 * any publicId that isn't a configured Cloudinary asset.
 */
export const mockVehicles: Vehicle[] = [
  {
    id: "mock-1",
    slug: "2019-ford-transit-custom-2-0-tdci-grantham-x7k2",
    status: "available",
    vehicleType: "van",
    reg: "YX19 ABC",
    make: "Ford",
    model: "Transit Custom",
    variant: "2.0 TDCi 130ps L1H1 Limited",
    year: 2019,
    mileage: 68450,
    price: 8995,
    vatStatus: "ex",
    fuel: "Diesel",
    transmission: "Manual",
    bodyType: "Panel Van",
    colour: "White",
    doors: 4,
    seats: 3,
    engineSize: "2.0L",
    owners: 2,
    motExpiry: "2026-06-14",
    description:
      "A well looked after Transit Custom Limited, finished in white with low mileage for its age. Ply-lined load area, side loading door, tow bar fitted and full service history. Ready for work - comes with 12 months MOT, a full service and our comprehensive in-house warranty.",
    features: [
      "Ply-lined load area",
      "Side loading door",
      "Tow bar",
      "Bluetooth",
      "Cruise control",
      "Parking sensors",
      "Full service history",
    ],
    images: [
      { publicId: "/vehicles/transit-custom/1.png", width: 1600, height: 1067 },
      { publicId: "/vehicles/transit-custom/2.png", width: 1600, height: 1067 },
    ],
    createdAt: "2025-08-01T09:00:00.000Z",
    updatedAt: "2025-09-10T09:00:00.000Z",
    soldAt: null,
  },
  {
    id: "mock-2",
    slug: "2018-volkswagen-golf-1-6-tdi-se-grantham-p3n8",
    status: "available",
    vehicleType: "car",
    reg: "MK18 DEF",
    make: "Volkswagen",
    model: "Golf",
    variant: "1.6 TDI SE Navigation",
    year: 2018,
    mileage: 54200,
    price: 9495,
    vatStatus: null,
    fuel: "Diesel",
    transmission: "Manual",
    bodyType: "Hatchback",
    colour: "Silver",
    doors: 5,
    seats: 5,
    engineSize: "1.6L",
    owners: 3,
    motExpiry: "2026-03-22",
    description:
      "A tidy, economical Golf SE Navigation in silver. Sat nav, DAB radio, alloy wheels and air conditioning throughout. A great first car or reliable family runaround, supplied with 12 months MOT, a full service and our comprehensive in-house warranty.",
    features: [
      "Satellite navigation",
      "DAB radio",
      "Alloy wheels",
      "Air conditioning",
      "Bluetooth",
      "Electric windows all round",
    ],
    images: [
      { publicId: "/vehicles/golf/1.png", width: 1600, height: 1067 },
      { publicId: "/vehicles/golf/2.png", width: 1600, height: 1067 },
    ],
    createdAt: "2025-08-05T09:00:00.000Z",
    updatedAt: "2025-09-12T09:00:00.000Z",
    soldAt: null,
  },
  {
    id: "mock-3",
    slug: "2017-mercedes-benz-sprinter-2-1-cdi-luton-grantham-h4t1",
    status: "reserved",
    vehicleType: "commercial",
    reg: "MX17 GHJ",
    make: "Mercedes-Benz",
    model: "Sprinter",
    variant: "2.1 CDI 314 Luton with Tail Lift",
    year: 2017,
    mileage: 92300,
    price: 11995,
    vatStatus: "ex",
    fuel: "Diesel",
    transmission: "Manual",
    bodyType: "Luton Van",
    colour: "White",
    doors: 3,
    seats: 3,
    engineSize: "2.1L",
    owners: 1,
    motExpiry: "2026-01-30",
    description:
      "A one-owner Sprinter Luton with tail lift, ideal for removals or heavy-goods delivery work. Recently serviced with a fresh MOT. Supplied with our comprehensive in-house warranty for extra peace of mind.",
    features: ["Tail lift", "Luton body", "Ply-lined load area", "Tow bar", "Bluetooth"],
    images: [
      { publicId: "/vehicles/sprinter/1.png", width: 1600, height: 1067 },
      { publicId: "/vehicles/sprinter/2.png", width: 1600, height: 1067 },
    ],
    createdAt: "2025-07-20T09:00:00.000Z",
    updatedAt: "2025-09-18T09:00:00.000Z",
    soldAt: null,
  },
  {
    id: "mock-4",
    slug: "2020-vauxhall-corsa-1-2-se-grantham-b9w5",
    status: "available",
    vehicleType: "car",
    reg: "LP20 KLM",
    make: "Vauxhall",
    model: "Corsa",
    variant: "1.2 SE",
    year: 2020,
    mileage: 31800,
    price: 8295,
    vatStatus: null,
    fuel: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    colour: "Red",
    doors: 5,
    seats: 5,
    engineSize: "1.2L",
    owners: 1,
    motExpiry: "2026-08-05",
    description:
      "A low-mileage, one-owner Corsa SE in eye-catching red. Cheap to run and insure, making it a perfect first car. Comes complete with 12 months MOT, a full service and our comprehensive in-house warranty.",
    features: ["Air conditioning", "Bluetooth", "DAB radio", "Electric windows", "Low insurance group"],
    images: [
      { publicId: "/vehicles/corsa/1.png", width: 1600, height: 1067 },
      { publicId: "/vehicles/corsa/2.png", width: 1600, height: 1067 },
    ],
    createdAt: "2025-08-25T09:00:00.000Z",
    updatedAt: "2025-09-20T09:00:00.000Z",
    soldAt: null,
  },
  {
    id: "mock-5",
    slug: "2016-ford-ranger-wildtrak-2-2-tdci-grantham-q6d3",
    status: "available",
    vehicleType: "commercial",
    reg: "FX16 NOP",
    make: "Ford",
    model: "Ranger",
    variant: "Wildtrak 2.2 TDCi Double Cab 4x4",
    year: 2016,
    mileage: 78900,
    price: 13995,
    vatStatus: "ex",
    fuel: "Diesel",
    transmission: "Manual",
    bodyType: "Pickup",
    colour: "Grey",
    doors: 4,
    seats: 5,
    engineSize: "2.2L",
    owners: 2,
    motExpiry: "2026-05-11",
    description:
      "A capable Wildtrak double cab with a hard tonneau cover, leather heated seats and full-time 4x4. Perfect for trade or leisure use. Supplied with 12 months MOT, a full service and our comprehensive in-house warranty.",
    features: [
      "4x4",
      "Heated leather seats",
      "Hard tonneau cover",
      "Reversing camera",
      "Sat nav",
      "Tow bar",
    ],
    images: [
      { publicId: "/vehicles/ranger/1.png", width: 1600, height: 1067 },
      { publicId: "/vehicles/ranger/2.png", width: 1600, height: 1067 },
    ],
    createdAt: "2025-08-12T09:00:00.000Z",
    updatedAt: "2025-09-22T09:00:00.000Z",
    soldAt: null,
  },
  {
    id: "mock-6",
    slug: "2019-nissan-qashqai-1-5-dci-acenta-grantham-r2v9",
    status: "sold",
    vehicleType: "car",
    reg: "NJ19 QRS",
    make: "Nissan",
    model: "Qashqai",
    variant: "1.5 dCi Acenta",
    year: 2019,
    mileage: 46700,
    price: 11495,
    vatStatus: null,
    fuel: "Diesel",
    transmission: "Manual",
    bodyType: "SUV",
    colour: "Blue",
    doors: 5,
    seats: 5,
    engineSize: "1.5L",
    owners: 2,
    motExpiry: "2026-02-18",
    description:
      "A spacious, well-equipped Qashqai Acenta in blue, popular for its comfort and economy. Full service history and two owners from new.",
    features: ["Cruise control", "Bluetooth", "Rear parking sensors", "Air conditioning", "Alloy wheels"],
    images: [
      { publicId: "/vehicles/qashqai/1.png", width: 1600, height: 1067 },
      { publicId: "/vehicles/qashqai/2.png", width: 1600, height: 1067 },
    ],
    createdAt: "2025-06-01T09:00:00.000Z",
    updatedAt: "2025-09-15T09:00:00.000Z",
    soldAt: "2025-09-15T09:00:00.000Z",
  },
]
